version: '3.8'

services:
  front-end:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_URL=http://ollama:11434

  ollama:
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    command: ["ollama", "run", "llama3.1"]

volumes:
  ollama: